config/routes.rb
Ooo::Application.routes.draw do
  resources :task_definitions
  resources :groups
  resources :tasks
  resources :roles
  resources :organizations, :shallow => true do
    resources :task_graph_definitions
  end

  resources :user_sessions do
    member do
      get 'new'
      post 'create'
      delete 'destroy'
    end
  end
      
  resources :users do
    member do
      get 'edit'
      get 'dashboard'
    end
  end

  mount OpenOrgPta::Engine => "/"

  root :to => 'users#dashboard'
end

app/models/task_graph_definition.rb
class TaskGraphDefinition < ActiveRecord::Base
  belongs_to :organization
  has_many :task_definitions, :class_name => "Task", :foreign_key => :task_graph_definition_id, :conditions => {:is_prototype => true}

  before_validation :clear_out_task_definitions
  validate :validate_definition

  default_scope where(:current_revision => true)

  attr_reader :new_id

  def initialize(*args)
    super

    @validated_tasks = []
  end

  def save
    if self.new_record? || !self.current_revision
      super
    else
      old_task_graph_definition = TaskGraphDefinition.unscoped.find(self.id)
      old_task_definitions = old_task_graph_definition.task_definitions

      begin
        self.transaction do
          new_old_task_graph_definition = self.class.new #old_task_graph_definition.dup
          new_old_task_graph_definition.current_revision = false
          new_old_task_graph_definition.save
          old_task_definitions.each do |task_definition|
            task_definition.current_revision = false
            task_definition.task_graph_definition = new_old_task_graph_definition
            task_definition.save
          end
          self.version = old_task_graph_definition.version + 1
          super
        end
      end
    end
  end

  private

  def clear_out_task_definitions
    return unless self.current_revision

    self.task_definitions = []
  end

  def validate_definition
    return unless self.current_revision

    if self.organization.nil?
      errors.add(:organization, "cannot be blank")
      return false
    end

    task_graph_builder = TaskGraphBuilder.new(self, organization)
    begin
      task_graph_builder.instance_eval(self.definition)
    rescue TaskGraphBuilder::Error => e
      errors.add(:definition, e.message)
      return false
    rescue Exception => e
      errors.add(:definition, e.message)
      return false
    end
  end


end

app/controllers/task_graph_definitions_controller.rb
class TaskGraphDefinitionsController < InheritedResources::Base
  belongs_to :organization, :shallow => true
end

app/helpers/task_graph_definitions_helper.rb
module TaskGraphDefinitionsHelper
end

app/views/task_graph_definitions/_form.html.haml
- if f.object.errors.any?
  Errors:
  %ul
  - f.object.errors.full_messages.each do |message|
    %li= message
= f.input :definition
= f.submit

app/views/task_graph_definitions/_summary.html.haml
= link_to(task_graph_definition.definition, task_graph_definition_path(task_graph_definition))

app/views/task_graph_definitions/edit.html.haml
Update Task Graph Definition
= simple_form_for @task_graph_definition do |f|
  = render :partial => "form", :locals => { :f => f }

app/views/task_graph_definitions/new.html.haml
Add New Task Graph Definition
= simple_form_for [@organization, TaskGraphDefinition.new] do |f|
  = render :partial => "form", :locals => { :f => f }

app/views/task_graph_definitions/show.html.haml
.title Task Graph Definition
%pre
  = @task_graph_definition.definition
.sub-title Task Definitions
%ul
  - @task_graph_definition.task_definitions.each do |task_definition|
    %li= render :partial => "task_definitions/summary", :locals => {:task_definition => task_definition}

= link_to("edit", edit_task_graph_definition_path(@task_graph_definition))
  