config/routes.rb
Ooo::Application.routes.draw do
  resources :task_definitions
  resources :groups
  resources :tasks
  resources :roles
  resources :organizations, :shallow => true do
    resources :task_graph_definitions
  end

  resources :user_sessions do
    member do
      get 'new'
      post 'create'
      delete 'destroy'
    end
  end
      
  resources :users do
    member do
      get 'edit'
      get 'dashboard'
    end
  end

  mount OpenOrgPta::Engine => "/"

  root :to => 'users#dashboard'
end

app/models/task_definition.rb
class TaskDefinition < ActiveRecord::Base
  belongs_to :organization
  belongs_to :role
  belongs_to :task_graph_definition

  has_many :dependers, class_name: 'TaskDefinitionDependency', foreign_key: :dependee_id
  has_many :dependees, class_name: 'TaskDefinitionDependency', foreign_key: :depender_id

  has_many :dependencies, through: :dependees, :source => :dependent_task_definition
  has_many :depending_on, through: :dependers, :source => :dependee_task_definition

  belongs_to  :parent_task_definition, :class_name => "TaskDefinition", :foreign_key => :parent_task_definition_id
  has_many    :child_task_definitions, :class_name => "TaskDefinition", :foreign_key => :parent_task_definition_id

  def performed_by(role_name)
    role = Role.where(:name => role_name.to_s).first
    if !role then
      role = Role.create(:name => role_name.to_s)
    end
    self.role = role
  end

  def starts_when(&block)
    @starts_when_proc = block
  end

  def completed_when(&block)
    @completed_when_proc = block
  end

  def on_activation(&block)
    @on_activation_proc = block
  end

  def on_completion(&block)
    @on_completion_proc = block
  end
end

app/controllers/task_definitions_controller.rb
class TaskDefinitionsController < ApplicationController
  # GET /task_definitions
  # GET /task_definitions.json
  def index
    @task_definitions = TaskDefinition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @task_definitions }
    end
  end

  # GET /task_definitions/1
  # GET /task_definitions/1.json
  def show
    @task_definition = TaskDefinition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task_definition }
    end
  end

  # GET /task_definitions/new
  # GET /task_definitions/new.json
  def new
    @task_definition = TaskDefinition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task_definition }
    end
  end

  # GET /task_definitions/1/edit
  def edit
    @task_definition = TaskDefinition.find(params[:id])
  end

  # POST /task_definitions
  # POST /task_definitions.json
  def create
    @task_definition = TaskDefinition.new(params[:task_definition])

    respond_to do |format|
      if @task_definition.save
        format.html { redirect_to @task_definition, notice: 'Task definition was successfully created.' }
        format.json { render json: @task_definition, status: :created, location: @task_definition }
      else
        format.html { render action: "new" }
        format.json { render json: @task_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /task_definitions/1
  # PUT /task_definitions/1.json
  def update
    @task_definition = TaskDefinition.find(params[:id])

    respond_to do |format|
      if @task_definition.update_attributes(params[:task_definition])
        format.html { redirect_to @task_definition, notice: 'Task definition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_definitions/1
  # DELETE /task_definitions/1.json
  def destroy
    @task_definition = TaskDefinition.find(params[:id])
    @task_definition.destroy

    respond_to do |format|
      format.html { redirect_to task_definitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/task_definitions_helper.rb
module TaskDefinitionsHelper
end

app/views/task_definitions/_form.html.erb
<%= form_for(@task_definition) do |f| %>
  <% if @task_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_definition.errors.count, "error") %> prohibited this task_definition from being saved:</h2>

      <ul>
      <% @task_definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :definition %><br />
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :depends_on_task_definition %><br />
    <%= f.number_field :depends_on_task_definition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_definitions/_summary.html.haml
.title= link_to(task_definition.name + (task_definition.child_tasks.present? ? " (with children)" : ""), task_path(task_definition))

app/views/task_definitions/edit.html.erb
<h1>Editing task_definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_definition %> |
<%= link_to 'Back', task_definitions_path %>

app/views/task_definitions/index.html.erb
<h1>Listing task_definitions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Definition</th>
    <th>Depends on task definition</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_definitions.each do |task_definition| %>
  <tr>
    <td><%= task_definition.name %></td>
    <td><%= task_definition.definition %></td>
    <td><%= task_definition.depends_on_task_definition %></td>
    <td><%= link_to 'Show', task_definition %></td>
    <td><%= link_to 'Edit', edit_task_definition_path(task_definition) %></td>
    <td><%= link_to 'Destroy', task_definition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task definition', new_task_definition_path %>

app/views/task_definitions/new.html.erb
<h1>New task_definition</h1>

<%= render 'form' %>

<%= link_to 'Back', task_definitions_path %>

app/views/task_definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task_definition.name %>
</p>

<p>
  <b>Definition:</b>
  <%= @task_definition.definition %>
</p>

<p>
  <b>Depends on task definition:</b>
  <%= @task_definition.depends_on_task_definition %>
</p>


<%= link_to 'Edit', edit_task_definition_path(@task_definition) %> |
<%= link_to 'Back', task_definitions_path %>