config/routes.rb
Ooo::Application.routes.draw do
  resources :task_definitions
  resources :groups
  resources :tasks
  resources :roles
  resources :organizations, :shallow => true do
    resources :task_graph_definitions
  end

  resources :user_sessions do
    member do
      get 'new'
      post 'create'
      delete 'destroy'
    end
  end
      
  resources :users do
    member do
      get 'edit'
      get 'dashboard'
    end
  end

  mount OpenOrgPta::Engine => "/"

  root :to => 'users#dashboard'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email_address, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create

  has_many :memberships
  has_many :tasks, :as => :owner
  has_many :assignments, :as => :assignable
  has_many :roles, :through => :assignments
  has_many :groups, :through => :memberships
  has_many :group_assignments, :through => :groups, :class_name => "Assignment", :source => :assignments
  has_many :group_roles, :through => :group_assignments, :class_name => "Role", :source => :role
  has_many :organizations, :through => :memberships
  has_many :organizational_groups, :through => :organizations, :source => :groups
  has_many :votes

  def self.ungrouped
    mt = Membership.arel_table
    user_ids_in_groups = Membership.where(mt[:group_id].eq(nil).not).map{|m| m.user_id}.reject{|u| u.nil?}
    ut = User.arel_table
    User.where(ut[:id].in(user_ids_in_groups).not)
  end

  def all_roles
    roles + group_roles
  end

  def all_roles_including(include_spec)
    roles.includes(include_spec) + group_roles.includes(include_spec)
  end

  def assigned_tasks
    self.tasks
  end

  def can_access_task_definition?(task_definition)
    roles.each do |role|
      if role.task_definitions.map{|task_def| task_def.id}.include?(task_definition.id)
        return true
      end
    end
    return false
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :show
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_summary.html.haml
user
= link_to(user.name, user_path(user))

app/views/users/dashboard.html.haml
Dashboard
- if current_user
  %div= "user email: #{current_user.email_address}"
  .organizations-headline= link_to "Organizations", organizations_path
  .organizations
    - current_user.organizations.each do |organization|
      = render :partial => "organizations/summary", :locals => {:organization => organization}
  .groups-headline= link_to "Groups", groups_path
  .groups
    - current_user.groups.each do |group|
      = render :partial => "groups/summary", :locals => {:group => group}
  .tasks-headline= link_to "Tasks", tasks_path
  .tasks
    - current_user.assigned_tasks.in_priority_order.each do |task|
      = render :partial => "tasks/summary", :locals => {:task => task, :include_actions => false}
  .start-tasks-headline Tasks To Start
  .start-tasks
    - task_definitions = current_user.all_roles_including(:task_definitions).inject([]) {|sum, role| sum + role.task_definitions.select{|task_def| task_def.dependencies.empty? && task_def.current_revision}}
    = form_tag '/tasks/new', :method => 'get' do
      = hidden_field_tag('user_id', current_user.id)
      .role-action= select_tag('task_id', options_from_collection_for_select(task_definitions, 'id', 'name_with_role'))
      = submit_tag('start task', :name => nil)
- else
  %div no current user

app/views/users/edit.html.haml
=simple_form_for(@user) do |f|
  .email_address= @user.email_address
  = f.input :name
  = f.button :submit

app/views/users/show.html.haml
User:
= @user.name
.tasks-title Tasks
- @user.tasks.each do |task|
  = link_to(task.name, task)
- @user.all_roles.includes(:task_definitions).each do |role|
  = form_tag '/tasks/new', :method => 'get' do
    = hidden_field_tag('user_id', @user.id)
    .role-action= select_tag('task_id', options_from_collection_for_select(role.task_definitions, 'id', 'name'))
    = submit_tag('start task', :name => nil)
.roles-title Direct Roles
- @user.roles.each do |role|
  .role-title= link_to(role.name, role)
.roles-title Group Roles 
- @user.group_roles.each do |role|
  .role-title= link_to(role.name, role)