config/routes.rb
Ooo::Application.routes.draw do
  resources :task_definitions
  resources :groups
  resources :tasks
  resources :roles
  resources :organizations, :shallow => true do
    resources :task_graph_definitions
  end

  resources :user_sessions do
    member do
      get 'new'
      post 'create'
      delete 'destroy'
    end
  end
      
  resources :users do
    member do
      get 'edit'
      get 'dashboard'
    end
  end

  mount OpenOrgPta::Engine => "/"

  root :to => 'users#dashboard'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :roles
  has_many :memberships
  has_many :task_definitions
  has_many :task_graph_definitions
  has_many :groups, :through => :memberships
  has_many :users, :through => :memberships
end

app/controllers/organizations_controller.rb
class OrganizationsController < InheritedResources::Base
  actions :index, :show, :new, :edit

protected
  def collection
    c = current_user.organizations
    puts "c = #{c.inspect}"
    c
  end

  def resource
    if params[:id] then
      current_user.organizations.find(params[:id])
    else
      organization = Organization.new
    end
  end
end

app/views/organizations/_form.html.haml
= f.input :name
= f.submit

app/views/organizations/_summary.html.haml
organization
= link_to(organization.name, organization_path(organization))

app/views/organizations/index.html.haml
Organizations
- collection.each do |organization|
  .organization= link_to organization.name, organization_path(organization)

app/views/organizations/new.html.haml
= simple_form_for resource do |f|
  = render :partial => "form", :locals => { :f => f }

app/views/organizations/show.html.haml
- organization = resource
.organization= "Name: #{organization.name}"
.section-title Groups
- organization.groups.occupied.each do |group|
  .group= render :partial => "groups/summary", :locals => {:group => group}
  - group.users.each do |user|
    .user= render :partial => "users/summary", :locals => {:user => user}
.section-title Users not in groups
- organization.users.ungrouped.each do |user|
  .user= render :partial => "users/summary", :locals => {:user => user}
.section-title Groups without users
- organization.groups.empty.each do |group|
  .user= render :partial => "groups/summary", :locals => {:group => group}
.section-title Roles
- organization.roles.each do |role|
  .role= render :partial => "roles/summary", :locals => {:role => role}
.section-title Task Graph Definitions
- organization.task_graph_definitions.each do |task_graph_definition|
  .task_graph_definition= render :partial => "task_graph_definitions/summary", :locals => { :task_graph_definition => task_graph_definition }
= link_to("Add Task Graph Definition", new_organization_task_graph_definition_path(organization))